Pre revert

diff --git a/meta-nanokvm/recipes-nanokvm/nanokvm-gadget/files/S03usbdev b/meta-nanokvm/recipes-nanokvm/nanokvm-gadget/files/S03usbdev
--- a/meta-nanokvm/recipes-nanokvm/nanokvm-gadget/files/S03usbdev
+++ b/meta-nanokvm/recipes-nanokvm/nanokvm-gadget/files/S03usbdev
@@ -4,10 +4,10 @@
 start_usb_dev() {
     . /etc/profile
     echo "usb mode: device"
-    cd /sys/kernel/config/usb_gadget
+    cd /sys/kernel/config/usb_gadget || { echo "Failed to cd into /sys/kernel/config/usb_gadget"; exit 1; }
 
     mkdir -p g0
-    cd g0
+    cd g0 || { echo "Failed to cd into /sys/kernel/config/usb_gadget/g0"; exit 1; }
 
     # echo 0x3346 > idVendor
     # echo 0x1009 > idProduct
@@ -125,7 +125,7 @@ start_usb_dev() {
         fi
         echo 1 >functions/hid.GS0/protocol
         echo 8 >functions/hid.GS0/report_length
-        echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 >functions/hid.GS0/report_desc
+        printf "%b" '\x05\x01\x09\x06\xa1\x01\x05\x07\x19\xe0\x29\xe7\x15\x00\x25\x01\x75\x01\x95\x08\x81\x02\x95\x01\x75\x08\x81\x03\x95\x05\x75\x01\x05\x08\x19\x01\x29\x05\x91\x02\x95\x01\x75\x03\x91\x03\x95\x06\x75\x08\x15\x00\x25\x65\x05\x07\x19\x00\x29\x65\x81\x00\xc0' >functions/hid.GS0/report_desc
         ln -s functions/hid.GS0 configs/c.1
 
         # mouse
@@ -158,7 +158,10 @@ start_usb_dev() {
     if [ ! -e /boot/udc.disable ]; then
         # Bind if not already bound (also re-binds after any unbind above).
         if [ -z "$(cat UDC 2>/dev/null | tr -d '[:space:]')" ]; then
-            ls /sys/class/udc/ | cat >UDC 2>/dev/null
+            for udc in /sys/class/udc/*.usb; do
+                echo "${udc##*/}" >UDC
+                break
+            done
         fi
     fi
     # /proc/cviusb/otg_role is a vendor OTG role-switch. On mainline the dwc2
